# -*- coding: utf-8 -*-
"""finel_V_diplom.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fAwjQapka8lP0aAZS4LfiS_RBA6TdzpY

# проверка
"""

from google.colab import drive
drive.mount('/content/drive')

# Работа с путями и файлами
from pathlib import Path
import shutil

# Статистика и структуры данных
from collections import Counter, defaultdict

# Работа с изображениями (позже пригодится)
import cv2

# Числа и массивы
import numpy as np

# Для визуализации (позже)
import matplotlib.pyplot as plt

DATASET_ROOT = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/final/dataset_classification")

print(DATASET_ROOT)
print("Существует:", DATASET_ROOT.exists())

TRAIN_DIR = DATASET_ROOT / "train"
VAL_DIR   = DATASET_ROOT / "val"
TEST_DIR  = DATASET_ROOT / "test"

print(TRAIN_DIR.exists(), VAL_DIR.exists(), TEST_DIR.exists())

from collections import defaultdict

def count_images_by_class(directory: Path):
    """
    Подсчитывает количество изображений в каждой подпапке (классе) и общее количество.
    Возвращает словарь с количеством по классам и общее число изображений.
    """
    image_extensions = {".jpg", ".jpeg", ".png", ".bmp", ".tiff"}
    class_counts = defaultdict(int)

    # Проходим по каждой подпапке
    for class_dir in directory.iterdir():
        if class_dir.is_dir():
            count = sum(1 for file in class_dir.rglob("*") if file.suffix.lower() in image_extensions)
            class_counts[class_dir.name] = count

    total_count = sum(class_counts.values())
    return class_counts, total_count

# Подсчёт для каждой выборки
train_classes, train_total = count_images_by_class(TRAIN_DIR)
val_classes, val_total     = count_images_by_class(VAL_DIR)
test_classes, test_total   = count_images_by_class(TEST_DIR)

# Вывод статистики
def print_stats(name, classes_dict, total):
    print(f"\n{name.upper()} выборка:")
    print(f"Общее количество изображений: {total}")
    print("Количество по классам:")
    for cls, cnt in classes_dict.items():
        print(f"  {cls}: {cnt}")

print_stats("Train", train_classes, train_total)
print_stats("Validation", val_classes, val_total)
print_stats("Test", test_classes, test_total)

import torch
import torchvision
print("PyTorch:", torch.__version__)
print("Torchvision:", torchvision.__version__)
print("CUDA доступна:", torch.cuda.is_available())

"""# аугм"""

import albumentations as A

def get_named_augmentations(img_size=224):
    return {
        "RandomResizedCrop": A.Compose([
            A.RandomResizedCrop(
                size=(img_size, img_size),
                scale=(0.9, 1.0),
                ratio=(0.95, 1.05),
                p=1.0
            )
        ]),

        "HorizontalFlip": A.Compose([
            A.HorizontalFlip(p=1.0)
        ]),

        "HueSaturationValue": A.Compose([
            A.HueSaturationValue(
                hue_shift_limit=(-40, 20),
                sat_shift_limit=(0, 90),
                val_shift_limit=(-20, 20),
                p=1.0
            )
        ]),


        "Rotate": A.Compose([
            A.Rotate(
                limit=3,
                p=1.0
            )
        ]),


        "Contrast": A.Compose([
            A.RandomBrightnessContrast(
                brightness_limit=0.0,
                contrast_limit=0.06,
                p=1.0
            )
        ])
    }

import random
import cv2
import matplotlib.pyplot as plt
from pathlib import Path


def visualize_augmentations_grid(
    image_paths,
    augmentations,
    img_size=224,
    max_samples=4,
    seed=42
):
    random.seed(seed)

    if len(image_paths) == 0:
        raise RuntimeError("Список изображений пуст.")

    sample_paths = random.sample(image_paths, k=min(max_samples, len(image_paths)))

    n_rows = len(sample_paths)
    n_cols = len(augmentations) + 1

    plt.figure(figsize=(3.5 * n_cols, 3.5 * n_rows))

    for r, img_path in enumerate(sample_paths):
        img = cv2.imread(str(img_path))
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        # ---- Original ----
        ax = plt.subplot(n_rows, n_cols, r * n_cols + 1)
        ax.imshow(img)
        ax.set_title("Original", fontsize=11)
        ax.axis("off")

        # ---- Augmentations ----
        for c, (name, aug) in enumerate(augmentations.items(), start=2):
            aug_img = aug(image=img)["image"]

            ax = plt.subplot(n_rows, n_cols, r * n_cols + c)
            ax.imshow(aug_img)
            ax.set_title(name, fontsize=11)
            ax.axis("off")

    plt.tight_layout()
    plt.show()

# Берём по одному примеру из разных классов
image_paths = []
for dir in sorted((DATASET_ROOT / "train").iterdir()):
    if dir.is_dir():
        imgs = list(dir.glob("*.jpg"))
        if imgs:
            image_paths.append(imgs[0])

augmentations = get_named_augmentations(img_size=224)

visualize_augmentations_grid(
    image_paths=image_paths,
    augmentations=augmentations,
    img_size=224,
    max_samples=4
)

"""# resnet18"""

import torch
from torch import nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
from tqdm import tqdm

# === Настройки ===
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 30
PATIENCE = 4
NUM_CLASSES = 12

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
print("Device:", device)

# === Трансформации ===
train_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406],
                         std=[0.229,0.224,0.225])
])

val_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406],
                         std=[0.229,0.224,0.225])
])

# === Датасеты ===
TRAIN_DIR = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/train")
VAL_DIR   = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/val")
TEST_DIR  = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/test")

train_ds = datasets.ImageFolder(TRAIN_DIR, transform=train_tfms)
val_ds   = datasets.ImageFolder(VAL_DIR, transform=val_tfms)
test_ds  = datasets.ImageFolder(TEST_DIR, transform=val_tfms)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

print("Классы:", train_ds.classes)

# === Модель ===
model = models.resnet18(weights=models.ResNet18_Weights.IMAGENET1K_V1)
model.fc = nn.Linear(model.fc.in_features, NUM_CLASSES)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.Adam(model.parameters(), lr=1e-3)

# === Функции обучения и оценки ===
def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    total_loss, correct, total = 0.0, 0, 0

    for imgs, labels in tqdm(loader, leave=False):
        imgs, labels = imgs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        total_loss += loss.item() * imgs.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return total_loss / total, correct / total


@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    total_loss, correct, total = 0.0, 0, 0

    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = model(imgs)
        loss = criterion(outputs, labels)

        total_loss += loss.item() * imgs.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return total_loss / total, correct / total

# === Обучение и запись метрик ===
best_val_acc = 0.0
best_val_loss = np.inf
epochs_no_improve = 0

train_losses, val_losses = [], []
train_accs, val_accs = [], []

BEST_MODEL_PATH = "best_resnet18.pth"

for epoch in range(1, EPOCHS + 1):
    train_loss, train_acc = train_one_epoch(
        model, train_loader, optimizer, criterion, device
    )
    val_loss, val_acc = evaluate(
        model, val_loader, criterion, device
    )

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    print(
        f"Epoch {epoch:02d} | "
        f"Train: loss={train_loss:.4f}, acc={train_acc:.3f} | "
        f"Val: loss={val_loss:.4f}, acc={val_acc:.3f}"
    )

    # === Сохраняем лучшие веса по val accuracy ===
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), BEST_MODEL_PATH)
        print("  Saved new best model (val acc)")

    # === Early Stopping по val loss ===
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"  No improvement in val loss ({epochs_no_improve}/{PATIENCE})")

    if epochs_no_improve >= PATIENCE:
        print(" Early stopping triggered")
        break

print("Loading best model weights...")
model.load_state_dict(torch.load(BEST_MODEL_PATH))
model.eval()

@torch.no_grad()
def predict(model, loader, device):
    model.eval()
    y_true, y_pred = [], []

    for imgs, labels in loader:
        imgs = imgs.to(device)
        outputs = model(imgs)
        preds = outputs.argmax(dim=1).cpu().numpy()

        y_true.extend(labels.numpy())
        y_pred.extend(preds)

    return np.array(y_true), np.array(y_pred)


y_true, y_pred = predict(model, test_loader, device)

print(
    classification_report(
        y_true,
        y_pred,
        target_names=train_ds.classes,
        digits=3
    )
)

@torch.no_grad()
def predict_probs(model, loader, device):
    """
    Возвращает вероятности и метки для ROC-AUC
    """
    model.eval()
    all_probs, all_labels = [], []

    for imgs, labels in loader:
        imgs = imgs.to(device)
        outputs = model(imgs)
        probs = nn.functional.softmax(outputs, dim=1).cpu().numpy()

        all_probs.extend(probs)
        all_labels.extend(labels.numpy())

    return np.array(all_labels), np.array(all_probs)

# === ROC-AUC ===
from sklearn.metrics import roc_curve, auc
from itertools import cycle

# Получаем вероятности и метки
y_true, y_probs = predict_probs(model, test_loader, device)
n_classes = len(train_ds.classes)

# One-hot кодирование
y_true_onehot = np.eye(n_classes)[y_true]

# Вычисляем ROC-AUC
fpr = dict()
tpr = dict()
roc_auc = dict()

for i in range(n_classes):
    fpr[i], tpr[i], _ = roc_curve(y_true_onehot[:, i], y_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

# График ROC-AUC
plt.figure(figsize=(10,8))
colors = cycle(['aqua', 'darkorange', 'cornflowerblue','green','red','purple','brown','pink','gray','olive','cyan','magenta'])

for i, color in zip(range(n_classes), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2, label=f"{train_ds.classes[i]} (AUC = {roc_auc[i]:.2f})")

plt.plot([0,1], [0,1], color='navy', lw=2, linestyle='--')
plt.xlim([0.0,1.0])
plt.ylim([0.0,1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-AUC для всех классов — ResNet18 ")
plt.legend(loc="lower right")
plt.show()

plt.figure(figsize=(12,5))

# === Loss по эпохам ===
plt.subplot(1,2,1)
plt.plot(train_losses, label="Train Loss", marker='o')
plt.plot(val_losses, label="Val Loss", marker='o')
plt.xlabel("Эпохи")
plt.ylabel("Loss")
plt.title("Loss по эпохам")
plt.grid(True)
plt.legend()

# === Accuracy по эпохам ===
plt.subplot(1,2,2)
plt.plot(train_accs, label="Train Acc", marker='o')
plt.plot(val_accs, label="Val Acc", marker='o')
plt.xlabel("Эпохи")
plt.ylabel("Accuracy")
plt.title("Accuracy по эпохам")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

import matplotlib.pyplot as plt
import torchvision

# Функция для отображения изображений с предсказаниями
def show_predictions(model, loader, device, classes, num_images=8):
    model.eval()
    images_shown = 0

    plt.figure(figsize=(15, 6))

    with torch.no_grad():
        for imgs, labels in loader:
            imgs, labels = imgs.to(device), labels.to(device)
            outputs = model(imgs)
            preds = outputs.argmax(dim=1)

            for i in range(len(imgs)):
                if images_shown >= num_images:
                    break

                img = imgs[i].cpu()
                img = img * torch.tensor([0.229,0.224,0.225]).view(3,1,1) + torch.tensor([0.485,0.456,0.406]).view(3,1,1)
                img = img.clamp(0,1)
                img = img.permute(1,2,0).numpy()  # C,H,W -> H,W,C

                plt.subplot(2, (num_images+1)//2, images_shown+1)
                plt.imshow(img)
                plt.axis('off')
                plt.title(f"True: {classes[labels[i]]}\nPred: {classes[preds[i]]}", fontsize=10)

                images_shown += 1

            if images_shown >= num_images:
                break

    plt.tight_layout()
    plt.show()

# Вызов функции для тестовых изображений
show_predictions(model, test_loader, device, train_ds.classes, num_images=8)

from sklearn.metrics import confusion_matrix
import seaborn as sns
import matplotlib.pyplot as plt
import numpy as np

# Получаем предсказания
y_pred = np.argmax(y_probs, axis=1)

# Строим матрицу ошибок
cm = confusion_matrix(y_true, y_pred)

plt.figure(figsize=(12,10))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues", xticklabels=train_ds.classes, yticklabels=train_ds.classes)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix для модели ResNet18")
plt.show()

"""# EfficientNet-B0"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix
import seaborn as sns
from tqdm import tqdm

NUM_CLASSES = 12
IMG_SIZE = 224
BATCH_SIZE = 32
EPOCHS = 30
PATIENCE = 4
device = "cuda" if torch.cuda.is_available() else "cpu"

print("Device:", device)

# === Трансформации ===
train_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406],
                         std=[0.229,0.224,0.225])
])

val_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406],
                         std=[0.229,0.224,0.225])
])

TRAIN_DIR = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/train")
VAL_DIR   = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/val")
TEST_DIR  = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/test")

train_ds = datasets.ImageFolder(TRAIN_DIR, transform=train_tfms)
val_ds   = datasets.ImageFolder(VAL_DIR, transform=val_tfms)
test_ds  = datasets.ImageFolder(TEST_DIR, transform=val_tfms)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

print("Классы:", train_ds.classes)

model = models.efficientnet_b0(weights=models.EfficientNet_B0_Weights.IMAGENET1K_V1)

# Меняем классификатор под NUM_CLASSES
in_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(in_features, NUM_CLASSES)
model = model.to(device)

criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-4)

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    running_loss, correct, total = 0.0, 0, 0

    for imgs, labels in tqdm(loader, leave=False):
        imgs, labels = imgs.to(device), labels.to(device)

        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()

        running_loss += loss.item() * imgs.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return running_loss / total, correct / total


@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0

    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = model(imgs)
        loss = criterion(outputs, labels)

        running_loss += loss.item() * imgs.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)

    return running_loss / total, correct / total


@torch.no_grad()
def predict_probs(model, loader, device):
    model.eval()
    all_probs, all_labels = [], []

    for imgs, labels in loader:
        imgs = imgs.to(device)
        outputs = model(imgs)
        probs = nn.functional.softmax(outputs, dim=1).cpu().numpy()
        all_probs.extend(probs)
        all_labels.extend(labels.numpy())

    return np.array(all_labels), np.array(all_probs)

best_val_acc = 0.0
best_val_loss = np.inf
epochs_no_improve = 0

train_losses, val_losses = [], []
train_accs, val_accs = [], []

BEST_MODEL_PATH = "best_efficientnet_b0.pth"

for epoch in range(1, EPOCHS+1):
    train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion, device)
    val_loss, val_acc = evaluate(model, val_loader, criterion, device)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    print(f"Epoch {epoch:02d} | Train: loss={train_loss:.4f}, acc={train_acc:.3f} | Val: loss={val_loss:.4f}, acc={val_acc:.3f}")

    # Сохраняем лучшие веса по val accuracy
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), BEST_MODEL_PATH)
        print("   Saved new best model (val acc)")

    # Early Stopping по val_loss
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"   No improvement in val loss ({epochs_no_improve}/{PATIENCE})")

    if epochs_no_improve >= PATIENCE:
        print(" Early stopping triggered")
        break

print("Loading best model weights...")
model.load_state_dict(torch.load(BEST_MODEL_PATH))
model.eval()

@torch.no_grad()
def predict(model, loader, device):
    model.eval()
    y_true, y_pred = [], []

    for imgs, labels in loader:
        imgs = imgs.to(device)
        outputs = model(imgs)
        preds = outputs.argmax(dim=1).cpu().numpy()
        y_true.extend(labels.numpy())
        y_pred.extend(preds)

    return np.array(y_true), np.array(y_pred)

y_true, y_pred = predict(model, test_loader, device)

print(classification_report(y_true, y_pred, target_names=train_ds.classes, digits=3))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(12,10))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=train_ds.classes, yticklabels=train_ds.classes)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix — EfficientNet-B0 ")
plt.show()

from sklearn.metrics import roc_curve, auc
from itertools import cycle

y_true_onehot = np.eye(NUM_CLASSES)[y_true]

fpr = dict()
tpr = dict()
roc_auc = dict()
for i in range(NUM_CLASSES):
    fpr[i], tpr[i], _ = roc_curve(y_true_onehot[:, i], y_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

plt.figure(figsize=(10,8))
colors = cycle(['aqua', 'darkorange', 'cornflowerblue','green','red','purple','brown','pink','gray','olive','cyan','magenta'])
for i, color in zip(range(NUM_CLASSES), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2, label=f"{train_ds.classes[i]} (AUC = {roc_auc[i]:.2f})")

plt.plot([0,1], [0,1], color='navy', lw=2, linestyle='--')
plt.xlim([0,1])
plt.ylim([0,1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-AUC для всех классов — EfficientNet-B0 ")
plt.legend(loc="lower right")
plt.show()

plt.figure(figsize=(12,5))

# === Loss по эпохам ===
plt.subplot(1,2,1)
plt.plot(train_losses, label="Train Loss", marker='o')
plt.plot(val_losses, label="Val Loss", marker='o')
plt.xlabel("Эпохи")
plt.ylabel("Loss")
plt.title("Loss по эпохам")
plt.grid(True)
plt.legend()

# === Accuracy по эпохам ===
plt.subplot(1,2,2)
plt.plot(train_accs, label="Train Acc", marker='o')
plt.plot(val_accs, label="Val Acc", marker='o')
plt.xlabel("Эпохи")
plt.ylabel("Accuracy")
plt.title("Accuracy по эпохам")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

"""# EfficientNet-B2"""

import torch
import torch.nn as nn
from torch.utils.data import DataLoader
from torchvision import datasets, transforms, models
from pathlib import Path

import numpy as np
import matplotlib.pyplot as plt
from sklearn.metrics import classification_report, confusion_matrix, roc_curve, auc
import seaborn as sns
from itertools import cycle
from tqdm import tqdm

NUM_CLASSES = 12
IMG_SIZE = 260       # EfficientNet-B2 использует 260x260
BATCH_SIZE = 32
EPOCHS = 30
PATIENCE = 4
device = "cuda" if torch.cuda.is_available() else "cpu"
print("Device:", device)

# Трансформации для EfficientNet-B2
train_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406],
                         std=[0.229,0.224,0.225])
])

val_tfms = transforms.Compose([
    transforms.Resize((IMG_SIZE, IMG_SIZE)),
    transforms.ToTensor(),
    transforms.Normalize(mean=[0.485,0.456,0.406],
                         std=[0.229,0.224,0.225])
])

TRAIN_DIR = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/train")
VAL_DIR   = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/val")
TEST_DIR  = Path("/content/drive/MyDrive/foraminifers/Final_version_of_the_database/diplom/datasets/test")

train_ds = datasets.ImageFolder(TRAIN_DIR, transform=train_tfms)
val_ds   = datasets.ImageFolder(VAL_DIR, transform=val_tfms)
test_ds  = datasets.ImageFolder(TEST_DIR, transform=val_tfms)

train_loader = DataLoader(train_ds, batch_size=BATCH_SIZE, shuffle=True, num_workers=2)
val_loader   = DataLoader(val_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)
test_loader  = DataLoader(test_ds, batch_size=BATCH_SIZE, shuffle=False, num_workers=2)

print("Классы:", train_ds.classes)

# Загружаем EfficientNet-B2
model = models.efficientnet_b2(weights=models.EfficientNet_B2_Weights.IMAGENET1K_V1)

in_features = model.classifier[1].in_features
model.classifier[1] = nn.Linear(in_features, NUM_CLASSES)

model = model.to(device)
criterion = nn.CrossEntropyLoss()
optimizer = torch.optim.AdamW(model.parameters(), lr=3e-4, weight_decay=1e-4)

def train_one_epoch(model, loader, optimizer, criterion, device):
    model.train()
    running_loss, correct, total = 0.0, 0, 0
    for imgs, labels in tqdm(loader, leave=False):
        imgs, labels = imgs.to(device), labels.to(device)
        optimizer.zero_grad()
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        loss.backward()
        optimizer.step()
        running_loss += loss.item() * imgs.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)
    return running_loss / total, correct / total

@torch.no_grad()
def evaluate(model, loader, criterion, device):
    model.eval()
    running_loss, correct, total = 0.0, 0, 0
    for imgs, labels in loader:
        imgs, labels = imgs.to(device), labels.to(device)
        outputs = model(imgs)
        loss = criterion(outputs, labels)
        running_loss += loss.item() * imgs.size(0)
        preds = outputs.argmax(dim=1)
        correct += (preds == labels).sum().item()
        total += labels.size(0)
    return running_loss / total, correct / total

@torch.no_grad()
def predict_probs(model, loader, device):
    model.eval()
    all_probs, all_labels = [], []
    for imgs, labels in loader:
        imgs = imgs.to(device)
        outputs = model(imgs)
        probs = nn.functional.softmax(outputs, dim=1).cpu().numpy()
        all_probs.extend(probs)
        all_labels.extend(labels.numpy())
    return np.array(all_labels), np.array(all_probs)

best_val_acc = 0.0
best_val_loss = np.inf
epochs_no_improve = 0

train_losses, val_losses = [], []
train_accs, val_accs = [], []

BEST_MODEL_PATH = "best_efficientnet_b2.pth"

for epoch in range(1, EPOCHS+1):
    train_loss, train_acc = train_one_epoch(model, train_loader, optimizer, criterion, device)
    val_loss, val_acc = evaluate(model, val_loader, criterion, device)

    train_losses.append(train_loss)
    val_losses.append(val_loss)
    train_accs.append(train_acc)
    val_accs.append(val_acc)

    print(f"Epoch {epoch:02d} | Train: loss={train_loss:.4f}, acc={train_acc:.3f} | Val: loss={val_loss:.4f}, acc={val_acc:.3f}")

    # Сохраняем лучшие веса по val accuracy
    if val_acc > best_val_acc:
        best_val_acc = val_acc
        torch.save(model.state_dict(), BEST_MODEL_PATH)
        print("   Saved new best model (val acc)")

    # Early Stopping по val_loss
    if val_loss < best_val_loss:
        best_val_loss = val_loss
        epochs_no_improve = 0
    else:
        epochs_no_improve += 1
        print(f"  No improvement in val loss ({epochs_no_improve}/{PATIENCE})")
    if epochs_no_improve >= PATIENCE:
        print(" Early stopping triggered")
        break

print("Loading best model weights...")
model.load_state_dict(torch.load(BEST_MODEL_PATH))
model.eval()

@torch.no_grad()
def predict(model, loader, device):
    model.eval()
    y_true, y_pred = [], []
    for imgs, labels in loader:
        imgs = imgs.to(device)
        outputs = model(imgs)
        preds = outputs.argmax(dim=1).cpu().numpy()
        y_true.extend(labels.numpy())
        y_pred.extend(preds)
    return np.array(y_true), np.array(y_pred)

y_true, y_pred = predict(model, test_loader, device)

print(classification_report(y_true, y_pred, target_names=train_ds.classes, digits=3))

cm = confusion_matrix(y_true, y_pred)
plt.figure(figsize=(12,10))
sns.heatmap(cm, annot=True, fmt="d", cmap="Blues",
            xticklabels=train_ds.classes, yticklabels=train_ds.classes)
plt.xlabel("Predicted")
plt.ylabel("True")
plt.title("Confusion Matrix — EfficientNet-B2 ")
plt.show()

y_true_onehot = np.eye(NUM_CLASSES)[y_true]

fpr = dict()
tpr = dict()
roc_auc = dict()
y_true_probs = predict_probs(model, test_loader, device)[1]

for i in range(NUM_CLASSES):
    fpr[i], tpr[i], _ = roc_curve(y_true_onehot[:, i], y_true_probs[:, i])
    roc_auc[i] = auc(fpr[i], tpr[i])

plt.figure(figsize=(10,8))
colors = cycle(['aqua', 'darkorange', 'cornflowerblue','green','red','purple','brown','pink','gray','olive','cyan','magenta'])
for i, color in zip(range(NUM_CLASSES), colors):
    plt.plot(fpr[i], tpr[i], color=color, lw=2, label=f"{train_ds.classes[i]} (AUC = {roc_auc[i]:.2f})")

plt.plot([0,1], [0,1], color='navy', lw=2, linestyle='--')
plt.xlim([0,1])
plt.ylim([0,1.05])
plt.xlabel("False Positive Rate")
plt.ylabel("True Positive Rate")
plt.title("ROC-AUC для всех классов — EfficientNet-B2 ")
plt.legend(loc="lower right")
plt.show()

plt.figure(figsize=(12,5))

plt.subplot(1,2,1)
plt.plot(train_losses, label="Train Loss", marker='o')
plt.plot(val_losses, label="Val Loss", marker='o')
plt.xlabel("Эпохи")
plt.ylabel("Loss")
plt.title("Loss по эпохам")
plt.grid(True)
plt.legend()

plt.subplot(1,2,2)
plt.plot(train_accs, label="Train Acc", marker='o')
plt.plot(val_accs, label="Val Acc", marker='o')
plt.xlabel("Эпохи")
plt.ylabel("Accuracy")
plt.title("Accuracy по эпохам")
plt.grid(True)
plt.legend()

plt.tight_layout()
plt.show()

